### ISSUE TITLE
Better fullscreen behavior

### ISSUE THREAD

**Issue by toji** [toji/chrome-webvr-issues#1]
Currently the WebVR API uses very hacky (probably insecure) behavior to move the entire browser window over to the HMD just before going fullscreen, which produces the desired effect of automatically sending the content to the right display but isn't a great user experience because the broswer window just disappears without warning from the main display until you hit escape.

We should figure out a way to move only the VR content, leaving the rest of the window in place. Ideally we would also have a placeholder element left in place of the VR content that instructs the users to put on the HMD to see the content and how to exit out of that mode. This element should ideally be able to be hidden by developers and replaced with their own page appropriate filler content.

**Comment by slawrence** [comment]
Hi Brandon,

I am attempting to use mouse clicks in my WebVR application to register events, but have been unsuccessful getting the pointerlock API to lock the mouse to the canvas when entering fullscreen with the vrDisplay params, likely because of the window is moved over to the HMD in Chromium? The mouse is hidden for a sec but then as soon as a click occurs it usually refocuses the window or desktop underneath where the browser window used to be.

I've tried requesting pointerlock on the window before and after the fullscreen occurs with no luck. Is  what I'm trying to achieve impossible with the current fullscreen behavior described here?

Thanks in advance for any help!

**Comment by cvan** [comment]
This can probably be closed in favour of [the new WebVR API spec proposal](https://mozvr.github.io/webvr-spec/).

**Comment by toji** [comment]
Agreed.
