### ISSUE TITLE
Webvr not working with oculus rift cv1 

### ISSUE THREAD

**Issue by aearanky** [toji/chrome-webvr-issues#115]
I am facing this issue:
Oculus consumer version cv1 and
here is my config:
Windows 10,
Oculus Platform Runtime SDK 1.9
Chromimum build from https://webvr.info/get-chrome/ Oct 29th, Web
webvr flag set in the chromium browser
"unknown source allowed" in oculus

Tried the same on firefox developer edition.

when i navigate to https://toji.github.io/webvr-samples/02-stereo-rendering.html
I can see the browser detecting the HMD, and rendering moves in the browser as i move my rift around.

But when i try to view this experience inside my oculus it always shows message:
"Sorry chrome.exe is taking a while to load."

Can someone please post a solution?

**Comment by toji** [comment]
Sample #2 is not intended to present anything to the headset. Try sample #3 instead: https://webvr.info/samples/03-vr-presentation.html

**Comment by SprinterSports** [comment]
Hi Toji,
Where is more of this material like sample #3 that works in my oculus DK2????

I have tried looking for other sites with VR  on the web and nothing seems to work (except sample #3 so far - at least I know webVR definitely works!!!)

[MY background need: I am hoping to view google streetview in Oculus. Will that be possible? (I know it sounds illogical with the streetview app but I need it on Oculus due to the movement (or lack of it by the user). And every app that someone claimed over the past couple of years making Streetview work in Oculus has been a total waste of time.

Can webVR work to allow  streetview to actually work on Oculus?

Thanks,
David

**Comment by toji** [comment]
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*
