### ISSUE TITLE
Is Chrome Dev on Android suitable for filing bugs against this repo?

### ISSUE THREAD

**Issue by stuartpb** [toji/chrome-webvr-issues#63]
Is the Chrome Dev release for Android up-to-date as far as WebVR is concerned, or do I need to be running the APK from https://webvr.info/get-chrome/?

**Comment by toji** [comment]
Bleh, sorry for the slow response. Chrome Dev is not *quite* up-to-date with WebVR 1.0 but I believe it should get there Real Soon Now™. Unfortunately I haven't been keeping the APK up to date either, because on Android I've been focused until recently on making sure the polyfill is robust. So I guess that means that nothing re: a native Android implementation is in a great state. :P

Feel free to submit bugs and make sure you note what version they came from. I might have to close some as "Already fixed" but I don't mind that.
